name: Build Tracks

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Scoop - setup - build
        shell: pwsh
        run: |
            Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
            Invoke-RestMethod -Uri https://get.scoop.sh | Invoke-Expression
            scoop install just
            just deps
            make
            gcc -E -x c tracks.pnml > tracks.nml
            nmlc tracks.nml --grf=china-set-tracks.grf

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.4.0
        with:
          name: chinas-set-tracks.grf
          path: ./china-set-tracks.grf
